---
title: "Midterm 2"
author: "Keven Lin"
date: "04/11/2022"
output: html_notebook
---

```{r}
library(tidyr)
```

```{R}
# A retrospective sample of males in a heart-disease high-risk region
# of the Western Cape, South Africa. There are roughly two controls per
# case of CHD. Many of the CHD positive men have undergone blood
# pressure reduction treatment and other programs to reduce their risk
# factors after their CHD event. In some cases the measurements were
# made after these treatments. These data are taken from a larger
# dataset, described in  Rousseauw et al, 1983, South African Medical
# Journal. 
# 
# sbp		systolic blood pressure
# tobacco		cumulative tobacco (kg)
# ldl		low densiity lipoprotein cholesterol
# adiposity
# famhist		family history of heart disease (Present, Absent)
# typea		type-A behavior
# obesity
# alcohol		current alcohol consumption
# age		age at onset
# chd		response, coronary heart disease
#

# To read into R:
heart = read.table('SAheart.data', sep=",",head=T,row.names=1)

```

Question 2: 

a. 

```{r}
model = glm(chd ~ age, data = heart, family=binomial)
summary(model)
```


b. 

```{r}
b0 = -3.521710
b1 = 0.064108
x = 50

p = exp(b0 + b1 * x) / (1 + exp(b0 + b1 * x))
p
```

c. 

```{r}
n =  dim(heart)[1]
prob = rep(0,100)
B = 100

for(b in 1:B){
  index = sample(1:n,n,replace=TRUE)
  bootsample = heart[index,]
  glm.fit = glm(chd~age, data = bootsample, family=binomial)
  beta_0 = coef(glm.fit)[1]
  beta_1 = coef(glm.fit)[2]

  prob[b] = (exp(beta_0 + beta_1 * x))/(1 + exp(beta_0 + beta_1 * x))
}

sqrt(sum((prob-mean(ps))^2)/(B-1))
```

d. 

```{r}
b0 = -3.521710
b1 = 0.064108
x = 55

p = exp(b0 + b1 * x) / (1 + exp(b0 + b1 * x))
p
```

3.

a. 

```{r}
temp = subset (heart, select = -famhist)
test = temp[1:100, ]
train = temp[101:462, ]

trainModel = glm(chd ~ ., data = train, family = binomial)
probabilities = trainModel %>% predict(train, type = "response")
names(probabilities) = NULL
head(probabilities, 10)
```

b. 

```{r}
testModel = glm(chd~., data=test, family='binomial')#, subset=train
prob = predict(glm.fit,test,type='response') 
n=dim(test)[1]
pred = rep(0,n)
pred[glm.prob >0.5] = 1
table(pred,test$chd)
1-mean(pred == test$chd)
```

```{r}
testModel = glm(chd~., data=test, family='binomial')#, subset=train
prob = predict(glm.fit,test,type='response') 
n=dim(test)[1]
pred = rep(0,n)
pred[glm.prob >.7] = 1
table(pred,test$chd)
1-mean(pred == test$chd)
```